[build-system]
requires = ["poetry>=0.9"]

[tool.poetry]
name = "my_project"
version = "0.1.0"
description = "This is my python project."
authors = ["Your Name <your@email.com>"]

readme = 'README.md'

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.6"