[build-system]
requires = ["poetry>=0.9"]

[tool.poetry]
name = "wuergmich"
version = "0.1.0"
description = "This is my python project."
authors = ["Duomilia <your@email.com>"]

readme = 'README.md'

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^3.10"